name: Issue Enhancement
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  enhance-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
          configuration-path: .github/auto_assign.yml