name: Issue and PR Enhancement
on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: ${{ secrets.PAT_TOKEN }}
          configuration-path: .github/auto_assign.yml